app:
  name: "PythonSearchApp"
  version: "2.2.1"

search:
  engines:
    google:
      enabled: true
      max_pages: 3
    duckduckgo:
      enabled: true
      max_pages: 3

scraping:
  max_emails_per_site: 5
  max_phones_per_site: 3
  request_delay: 2.0
  timeout: 30
  results_per_term_limit: 1200

retry:
  max_attempts: 3
  base_delay: 1.0
  backoff_factor: 2.0
  max_delay: 60.0

performance:
  tracking_enabled: true
  metrics_retention_hours: 24

delays:
  # Delays para Google (mínimo seguro)
  google:
    page_load_min: 1.5
    page_load_max: 2.5
    scroll_min: 0.8
    scroll_max: 1.2
    search_dwell_min: 1.0
    search_dwell_max: 2.0
  
  # Delays para DuckDuckGo (otimizado)
  duckduckgo:
    page_load_min: 0.8
    page_load_max: 1.5
    scroll_min: 0.3
    scroll_max: 0.8
    search_dwell_min: 0.5
    search_dwell_max: 1.2

mode:
  is_test: true
  complete_threshold: 1000

geolocation:
  reference_cep: "01310-100"  # CEP de referência para cálculo de distâncias
  enabled: true